groups:
  - name: AppAlerts
    rules:
      - alert: WARNING-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 10
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: CRITICAL-HighThroughput
        expr: rate(hello_info_count_total[1m]) > 50
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: Increased info retrieval rate {{ $labels.value}} {{ $value }}
          description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: CRITICAL-ApiIncreasedErrorRate
        expr: rate(exceptions_internalServerErrors_total[1m]) > 20
        for: 10s
        labels:
          severity: critical
        annotations:
          summary: High API Internal server errors {{ $labels.value}} {{ $value }}
          description: "The APIs are experiencing a high level of error rates\n VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
